# Generated by Django 4.0.2 on 2022-04-10 06:07

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پاک شدن')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='پاک شده')),
                ('first_name', models.CharField(max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('password', models.CharField(max_length=40, validators=[core.validators.validate_password], verbose_name='رمز عبور')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتری ها',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پاک شدن')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='پاک شده')),
                ('province', models.CharField(max_length=20, verbose_name='استان')),
                ('city', models.CharField(max_length=20, verbose_name='شهر')),
                ('alley', models.CharField(max_length=50, verbose_name='محله')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
    ]
