# Generated by Django 4.0.2 on 2022-02-16 07:27

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=40, validators=[core.validators.validate_password], verbose_name='گذرواژه'),
        ),
    ]
