# Generated by Django 4.0.2 on 2022-04-10 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پاک شدن')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='پاک شده')),
                ('cat_title', models.CharField(max_length=30, verbose_name='عنوان دسته بندی')),
                ('about', models.TextField(max_length=500, verbose_name='درباره دسته بندی')),
                ('parent_cat', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='دسته بندی مرجع')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پاک شدن')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='پاک شده')),
                ('discount_title', models.CharField(max_length=20, verbose_name='عنوان تخفیف')),
                ('discount_amount', models.PositiveIntegerField(verbose_name='میزان تخفیف')),
                ('type', models.CharField(choices=[('قیمت', 'قیمت'), ('درصدی', 'قیمتی')], max_length=10, verbose_name='نوع تخفیف')),
                ('max_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='بیشترین میزان تخفیف')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پاک شدن')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='پاک شده')),
                ('pro_name', models.CharField(max_length=40, verbose_name='نام محصول')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('brand', models.CharField(max_length=30, verbose_name='برند')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس محصول')),
                ('properties', models.TextField(max_length=1000, verbose_name='ویژگی ها')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='دسته بندی')),
                ('discount', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.discount', verbose_name='تخفیف')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['create_time'],
            },
        ),
    ]
