# Generated by Django 4.0.2 on 2022-02-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_title',
            field=models.CharField(max_length=20, verbose_name='discount_title'),
        ),
    ]
