# Generated by Django 4.0.2 on 2022-02-16 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیف ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['create_time'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='category',
            name='about',
            field=models.TextField(max_length=500, verbose_name='درباره دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_title',
            field=models.CharField(max_length=30, verbose_name='عنوان دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='category',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پاک شدن'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='پاک شده'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_cat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='دسته بندی مرجع'),
        ),
        migrations.AlterField(
            model_name='category',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پاک شدن'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_amount',
            field=models.PositiveIntegerField(verbose_name='میزان تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_title',
            field=models.CharField(max_length=20, verbose_name='عنوان تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='پاک شده'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='max_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='بیشترین میزان تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('قیمت', 'قیمت'), ('درصدی', 'قیمتی')], max_length=10, verbose_name='نوع تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=30, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پاک شدن'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.discount', verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='عکس محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='پاک شده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_name',
            field=models.CharField(max_length=40, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='properties',
            field=models.TextField(max_length=1000, verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی انبار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
    ]
