# Generated by Django 4.0.2 on 2022-02-15 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='basket_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.discountcode', verbose_name='basket_code'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('Canceled', 'canceled'), ('Unpaid', 'unpaid'), ('Paid', 'paid')], default='Unpaid', max_length=8, verbose_name='basket_status'),
        ),
    ]
