# Generated by Django 4.0.2 on 2022-02-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_basket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('Canceled', 'canceled'), ('Paid', 'paid'), ('Unpaid', 'unpaid')], default='Unpaid', max_length=8, verbose_name='basket_status'),
        ),
    ]
