# Generated by Django 4.0.2 on 2022-02-16 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_options_alter_discount_options_and_more'),
        ('customer', '0003_alter_address_options_alter_customer_options_and_more'),
        ('order', '0005_alter_basket_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'سبد', 'verbose_name_plural': 'سبدها'},
        ),
        migrations.AlterModelOptions(
            name='discountcode',
            options={'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کدهای تخفیف'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterField(
            model_name='basket',
            name='basket_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.discountcode', verbose_name='کد تخفیف سبد'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='basket_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='مشتری این سفارش'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پاک شدن'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='پاک شده'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('Paid', 'پرداخت شده'), ('Unpaid', 'پرداخت نشده'), ('Canceled', 'لغو شده')], default='Unpaid', max_length=8, verbose_name='وضعیت سبد'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code_amount',
            field=models.PositiveIntegerField(verbose_name='میزان تخفیف کد'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code_title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='عنوان کد'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پاک شدن'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='پاک شده'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.basket', verbose_name='سبد سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پاک شدن'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='پاک شده'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='number',
            field=models.PositiveIntegerField(verbose_name='تعداد سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
    ]
